#github workflow file for testing the code and pushing the image to hub
name: build-test-push

on:
  push:
    branches:
      - master
    paths-ignore:
      - "go-web-app-helm/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
  
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-golang:${{ github.run_id }}
      
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: build_push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' go-web-app-helm/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "pranaybablu024@gmail.com"
        git config --global user.name "pranayguevara8610"
        git add go-web-app-helm/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
